teleop:
  type: so101_leader
  port: COM9
  id: 2026-08-31_leader
  calibration_dir: ./calibration

robot:
  type: so101_follower
  port: COM8
  id: 2026-08-31_follower
  calibration_dir: ./calibration
  cameras:
    left_front:
      type: intelrealsense
      serial_number_or_name: "260322271459"
      width: 848
      height: 480
      fps: 30
      use_depth: false
    right_front:
      type: intelrealsense
      serial_number_or_name: "262822305610"
      width: 1280
      height: 720
      fps: 30
      use_depth: false

dataset:
  repo_id: <HF_USER>/so101_pick_place
  num_episodes: 20
  single_task: "Pick up the object and place it into the box"
  streaming_encoding: true

display_data: true
