teleop:
  type: so101_leader
  port: COM6
  id: 2026-08-31_leader
  calibration_dir: ./calibration

robot:
  type: so101_follower
  port: COM5
  id: 2026-08-31_follower
  calibration_dir: ./calibration

fps: 60
display_data: true
